# Medidas de posição e dispersão

## Base de dados

In [ ]:
import numpy as np
import statistics
from scipy import stats
import math

In [ ]:
dados = np.array([150, 151, 152, 152, 153, 154, 155, 155, 155, 155, 156, 156, 156,
                  157, 158, 158, 160, 160, 160, 160, 160, 161, 161, 161, 161, 162,
                  163, 163, 164, 164, 164, 165, 166, 167, 168, 168, 169, 170, 172,
                  173])

## Média aritmética simples

In [ ]:
dados.sum() / len(dados)

160.375

In [ ]:
dados.mean()

160.375

In [ ]:
statistics.mean(dados)

160

## Moda

In [ ]:
statistics.mode(dados)

160

In [ ]:
stats.mode(dados)

ModeResult(mode=array([160]), count=array([5]))

## Mediana

In [ ]:
dados_impar = [150, 151, 152, 152, 153, 154, 155, 155, 155]

### Cálculo manual (ímpar)

In [ ]:
posicao = len(dados_impar) / 2
posicao

4.5

In [ ]:
posicao = math.ceil(posicao)
posicao

5

In [ ]:
dados_impar[posicao - 1]

153

### Cálculo manual (par)

In [ ]:
posicao = len(dados) // 2
posicao

20

In [ ]:
dados[posicao - 1], dados[posicao]

(160, 160)

In [ ]:
mediana = (dados[posicao - 1] + dados[posicao]) / 2
mediana

160.0

### Bibliotecas

In [ ]:
np.median(dados_impar)

153.0

In [ ]:
np.median(dados)

160.0

In [ ]:
statistics.median(dados_impar)

153

In [ ]:
statistics.median(dados)

160.0

## Média aritmética ponderada

In [ ]:
notas = np.array([9, 8, 7, 3])
pesos = np.array([1, 2, 3, 4])

In [ ]:
(9 * 1 + 8 * 2 + 7 * 3 + 3 * 4) / (1 + 2 + 3 + 4)

5.8

In [ ]:
media_ponderada = (notas * pesos).sum() / pesos.sum()
media_ponderada

5.8

In [ ]:
np.average(notas, weights=pesos)

5.8

## Média aritmética, moda e mediana com distribuição de frequência (dados agrupados)

In [ ]:
dados = {'inferior': [150, 154, 158, 162, 166, 170],
         'superior': [154, 158, 162, 166, 170, 174],
         'fi': [5, 9, 11, 7, 5, 3]}

In [ ]:
import pandas as pd
dataset = pd.DataFrame(dados)
dataset

inferior  superior  fi
0       150       154   5
1       154       158   9
2       158       162  11
3       162       166   7
4       166       170   5
5       170       174   3

In [ ]:
dataset['xi'] = (dataset['superior'] + dataset['inferior']) / 2
dataset

inferior  superior  fi     xi
0       150       154   5  152.0
1       154       158   9  156.0
2       158       162  11  160.0
3       162       166   7  164.0
4       166       170   5  168.0
5       170       174   3  172.0

In [ ]:
dataset['fi.xi'] = dataset['fi'] * dataset['xi']
dataset

inferior  superior  fi     xi   fi.xi
0       150       154   5  152.0   760.0
1       154       158   9  156.0  1404.0
2       158       162  11  160.0  1760.0
3       162       166   7  164.0  1148.0
4       166       170   5  168.0   840.0
5       170       174   3  172.0   516.0

In [ ]:
dataset['Fi'] = 0
dataset

inferior  superior  fi     xi   fi.xi  Fi
0       150       154   5  152.0   760.0   0
1       154       158   9  156.0  1404.0   0
2       158       162  11  160.0  1760.0   0
3       162       166   7  164.0  1148.0   0
4       166       170   5  168.0   840.0   0
5       170       174   3  172.0   516.0   0

In [ ]:
frequencia_acumulada = []
somatorio = 0
for linha in dataset.iterrows():
  #print(linha[1])
  #print(linha[1][2])
  somatorio += linha[1][2]
  frequencia_acumulada.append(somatorio)

In [ ]:
frequencia_acumulada

[5.0, 14.0, 25.0, 32.0, 37.0, 40.0]

In [ ]:
dataset['Fi'] = frequencia_acumulada
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

### Média

In [ ]:
dataset['fi'].sum(), dataset['fi.xi'].sum()

(40, 6428.0)

In [ ]:
dataset['fi.xi'].sum() / dataset['fi'].sum()

160.7

### Moda

In [ ]:
dataset['fi'].max()

11

In [ ]:
dataset[dataset['fi'] == dataset['fi'].max()]

inferior  superior  fi     xi   fi.xi    Fi
2       158       162  11  160.0  1760.0  25.0

In [ ]:
dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

160.0

### Mediana

In [ ]:
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [ ]:
fi_2 = dataset['fi'].sum() / 2
fi_2

20.0

In [ ]:
limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0
for linha in dataset.iterrows():
  #print(linha)
  limite_inferior = linha[1][0]
  frequencia_classe = linha[1][2]
  id_frequencia_anterior = linha[0]
  if linha[1][5] >= fi_2:
    id_frequencia_anterior -= 1
    break

In [ ]:
limite_inferior, frequencia_classe, id_frequencia_anterior

(158.0, 11.0, 1)

In [ ]:
Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
Fi_anterior

14.0

In [ ]:
mediana = limite_inferior + ((fi_2 - Fi_anterior) * 4) / frequencia_classe
mediana

160.1818181818182

### Função completa

In [ ]:
def get_estatisticas(dataframe):
  media = dataset['fi.xi'].sum() / dataset['fi'].sum()
  moda = dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

  fi_2 = dataset['fi'].sum() / 2
  limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0
  for i, linha in enumerate(dataset.iterrows()):
    limite_inferior = linha[1][0]
    frequencia_classe = linha[1][2]
    id_frequencia_anterior = linha[0]
    if linha[1][5] >= fi_2:
      id_frequencia_anterior -= 1
      break
  Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
  mediana = limite_inferior + ((fi_2 - Fi_anterior) * 4) / frequencia_classe

  return media, moda, mediana

In [ ]:
get_estatisticas(dataset)

(160.7, 160.0, 160.1818181818182)

## Média geométrica, harmônica e quadrática

### Média geométrica

In [ ]:
from scipy.stats.mstats import gmean

In [ ]:
gmean(dados)

160.26958390038905

### Média harmônica

In [ ]:
from scipy.stats.mstats import hmean

In [ ]:
hmean(dados)

160.16471947994674

### Média quadrática

In [ ]:
def quadratic_mean(dados):
  return math.sqrt(sum(n * n for n in dados) / len(dados))

In [ ]:
quadratic_mean(dados)

160.48091786876097

## Quartis

In [ ]:
dados_impar = [150, 151, 152, 152, 153, 154, 155, 155, 155]

### Cálculo manual

In [ ]:
np.median(dados_impar)

153.0

In [ ]:
posicao_mediana = math.floor(len(dados_impar) / 2)
posicao_mediana

4

In [ ]:
esquerda = dados_impar[0:posicao_mediana]
esquerda

[150, 151, 152, 152]

In [ ]:
np.median(esquerda)

151.5

In [ ]:
direita = dados_impar[posicao_mediana + 1:]
direita

[154, 155, 155, 155]

In [ ]:
np.median(direita)

155.0

### Bibliotecas

#### numpy

In [ ]:
np.quantile(dados_impar, 0.5)

153.0

In [ ]:
np.quantile(dados_impar, 0.75)

155.0

In [ ]:
np.quantile(dados_impar, 0.25)

152.0

In [ ]:
esquerda2 = dados_impar[0:posicao_mediana + 1]
esquerda2

[150, 151, 152, 152, 153]

In [ ]:
np.median(esquerda2)

152.0

In [ ]:
np.quantile(dados, 0.25), np.quantile(dados, 0.50), np.quantile(dados, 0.75)

(155.75, 160.0, 164.0)

#### scipy

In [ ]:
stats.scoreatpercentile(dados, 25), stats.scoreatpercentile(dados, 50), stats.scoreatpercentile(dados, 75)

(155.75, 160.0, 164.0)

#### pandas

In [ ]:
import pandas as pd
dataset = pd.DataFrame(dados)
dataset.head()

0
0  150
1  151
2  152
3  152
4  153

In [ ]:
dataset.quantile([0.25, 0.5, 0.75])

0
0.25  155.75
0.50  160.00
0.75  164.00

In [ ]:
dataset.describe()

0
count   40.000000
mean   160.375000
std      5.903877
min    150.000000
25%    155.750000
50%    160.000000
75%    164.000000
max    173.000000

## Quartis com distribuição de frequência (dados agrupados)

In [ ]:
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [ ]:
def get_quartil(dataframe, q1 = True):
  if q1 == True:
    fi_4 = dataset['fi'].sum() / 4
  else:
    fi_4 = (3 * dataset['fi'].sum()) / 4
  
  limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0
  for linha in dataset.iterrows():
    limite_inferior = linha[1][0]
    frequencia_classe = linha[1][2]
    id_frequencia_anterior = linha[0]
    if linha[1][5] >= fi_4:
      id_frequencia_anterior -= 1
      break
  Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
  q = limite_inferior + ((fi_4 - Fi_anterior) * 4) / frequencia_classe

  return q

In [ ]:
get_quartil(dados), get_quartil(dados, q1 = False)

(156.22222222222223, 164.85714285714286)

## Percentis

In [ ]:
np.median(dados)

160.0

In [ ]:
np.quantile(dados, 0.5)

160.0

In [ ]:
np.percentile(dados, 50)

160.0

In [ ]:
np.percentile(dados, 5), np.percentile(dados, 10), np.percentile(dados, 90)

(151.95000000000002, 152.89999999999998, 168.1)

In [ ]:
stats.scoreatpercentile(dados, 5), stats.scoreatpercentile(dados, 10), stats.scoreatpercentile(dados, 90)

(151.95000000000002, 152.89999999999998, 168.1)

In [ ]:
import pandas as pd
dataset = pd.DataFrame(dados)
dataset.head()

0
0  150
1  151
2  152
3  152
4  153

In [ ]:
dataset.quantile([0.05, 0.10, 0.90])

0
0.05  151.95
0.10  152.90
0.90  168.10

## Exercício

In [ ]:
dataset = pd.read_csv('census.csv')

In [ ]:
dataset.head()

age          workclass  final-weight  ... hour-per-week  native-country  income
0   39          State-gov         77516  ...            40   United-States   <=50K
1   50   Self-emp-not-inc         83311  ...            13   United-States   <=50K
2   38            Private        215646  ...            40   United-States   <=50K
3   53            Private        234721  ...            40   United-States   <=50K
4   28            Private        338409  ...            40            Cuba   <=50K

[5 rows x 15 columns]

In [ ]:
dataset['age'].mean()

38.58164675532078

In [ ]:
stats.hmean(dataset['age'])

33.91874139089839

In [ ]:
from scipy.stats.mstats import gmean
gmean(dataset['age'])

36.210879158177256

In [ ]:
quadratic_mean(dataset['age'])

40.9218664329987

In [ ]:
dataset['age'].median()

37.0

In [ ]:
statistics.mode(dataset['age'])

36

## Medidas de dispersão

### Amplitude total e diferença interquartil

In [ ]:
dados

array([150, 151, 152, 152, 153, 154, 155, 155, 155, 155, 156, 156, 156,
       157, 158, 158, 160, 160, 160, 160, 160, 161, 161, 161, 161, 162,
       163, 163, 164, 164, 164, 165, 166, 167, 168, 168, 169, 170, 172,
       173])

In [ ]:
dados.max() - dados.min()

23

In [ ]:
q1 = np.quantile(dados, 0.25)
q3 = np.quantile(dados, 0.75)
q1, q3

(155.75, 164.0)

In [ ]:
diferenca_interquartil = q3 - q1
diferenca_interquartil

8.25

In [ ]:
inferior = q1 - (1.5 * diferenca_interquartil)
inferior

143.375

In [ ]:
superior = q3 + (1.5 * diferenca_interquartil)
superior

176.375

### Variância, desvio padrão e coeficiente de variação

In [ ]:
dados_impar = np.array([150, 151, 152, 152, 153, 154, 155, 155, 155])

#### Cálculo manual

In [ ]:
media = dados_impar.sum() / len(dados_impar)
media

153.0

In [ ]:
desvio = abs(dados_impar - media)
desvio

array([3., 2., 1., 1., 0., 1., 2., 2., 2.])

In [ ]:
desvio = desvio ** 2
desvio

array([9., 4., 1., 1., 0., 1., 4., 4., 4.])

In [ ]:
soma_desvio = desvio.sum()
soma_desvio

28.0

In [ ]:
v = soma_desvio / len(dados_impar)
v

3.111111111111111

In [ ]:
dp = math.sqrt(v)
dp

1.7638342073763937

In [ ]:
cv = (dp / media) * 100
cv

1.1528328152786886

In [ ]:
def get_variancia_desvio_padrao_coeficiente(dataset):
  media = dataset.sum() / len(dataset)
  desvio = abs(dados_impar - media)
  desvio = desvio ** 2
  soma_desvio = desvio.sum()
  variancia = soma_desvio / len(dados_impar)
  dp = math.sqrt(variancia)
  return variancia, dp, (dp / media) * 100

In [ ]:
get_variancia_desvio_padrao_coeficiente(dados_impar)

(3.111111111111111, 1.7638342073763937, 1.1528328152786886)

#### Bibliotecas

In [ ]:
np.var(dados_impar)

3.111111111111111

In [ ]:
np.std(dados_impar)

1.7638342073763937

In [ ]:
np.var(dados)

33.984375

In [ ]:
np.std(dados)

5.829611908180509

In [ ]:
statistics.variance(dados)

34

In [ ]:
statistics.stdev(dados)

5.830951894845301

In [ ]:
from scipy import ndimage
ndimage.variance(dados)

33.984375

In [ ]:
stats.tstd(dados, ddof = 0)

5.829611908180509

In [ ]:
stats.variation(dados_impar) * 100

1.1528328152786886

In [ ]:
stats.variation(dados) * 100

3.634987939629312

### Desvio padrão com dados agrupados

In [ ]:
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [ ]:
dataset['xi_2'] = dataset['xi'] * dataset['xi']
dataset

inferior  superior  fi     xi   fi.xi    Fi     xi_2
0       150       154   5  152.0   760.0   5.0  23104.0
1       154       158   9  156.0  1404.0  14.0  24336.0
2       158       162  11  160.0  1760.0  25.0  25600.0
3       162       166   7  164.0  1148.0  32.0  26896.0
4       166       170   5  168.0   840.0  37.0  28224.0
5       170       174   3  172.0   516.0  40.0  29584.0

In [ ]:
dataset['fi_xi_2'] = dataset['fi'] * dataset['xi_2']
dataset

inferior  superior  fi     xi   fi.xi    Fi     xi_2   fi_xi_2
0       150       154   5  152.0   760.0   5.0  23104.0  115520.0
1       154       158   9  156.0  1404.0  14.0  24336.0  219024.0
2       158       162  11  160.0  1760.0  25.0  25600.0  281600.0
3       162       166   7  164.0  1148.0  32.0  26896.0  188272.0
4       166       170   5  168.0   840.0  37.0  28224.0  141120.0
5       170       174   3  172.0   516.0  40.0  29584.0   88752.0

In [ ]:
dataset.columns

Index(['inferior', 'superior', 'fi', 'xi', 'fi.xi', 'Fi', 'xi_2', 'fi_xi_2'], dtype='object')

In [ ]:
colunas_ordenadas = ['inferior', 'superior', 'fi', 'xi', 'fi.xi', 'xi_2', 'fi_xi_2', 'Fi']

In [ ]:
dataset = dataset[colunas_ordenadas]
dataset

inferior  superior  fi     xi   fi.xi     xi_2   fi_xi_2    Fi
0       150       154   5  152.0   760.0  23104.0  115520.0   5.0
1       154       158   9  156.0  1404.0  24336.0  219024.0  14.0
2       158       162  11  160.0  1760.0  25600.0  281600.0  25.0
3       162       166   7  164.0  1148.0  26896.0  188272.0  32.0
4       166       170   5  168.0   840.0  28224.0  141120.0  37.0
5       170       174   3  172.0   516.0  29584.0   88752.0  40.0

In [ ]:
dp = math.sqrt(dataset['fi_xi_2'].sum() / dataset['fi'].sum() - math.pow(dataset['fi.xi'].sum() / dataset['fi'].sum(), 2))
dp

5.719265687131764

## Testes com algoritmos de classificação

In [ ]:
import pandas as pd
dataset = pd.read_csv('credit_data.csv')

In [ ]:
dataset.dropna(inplace=True)
dataset.shape

(1997, 5)

In [ ]:
dataset

i#clientid        income        age         loan  c#default
0              1  66155.925095  59.017015  8106.532131          0
1              2  34415.153966  48.117153  6564.745018          0
2              3  57317.170063  63.108049  8020.953296          0
3              4  42709.534201  45.751972  6103.642260          0
4              5  66952.688845  18.584336  8770.099235          1
...          ...           ...        ...          ...        ...
1995        1996  59221.044874  48.518179  1926.729397          0
1996        1997  69516.127573  23.162104  3503.176156          0
1997        1998  44311.449262  28.017167  5522.786693          1
1998        1999  43756.056605  63.971796  1622.722598          0
1999        2000  69436.579552  56.152617  7378.833599          0

[1997 rows x 5 columns]

In [ ]:
X = dataset.iloc[:, 1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [ ]:
y = dataset.iloc[:, 4].values
y

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
resultados_naive_bayes = []
resultados_logistica = []
resultados_forest = []
for i in range(30):
  X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.2,
                                                                    stratify = y, random_state = i)
  naive_bayes = GaussianNB()
  naive_bayes.fit(X_treinamento, y_treinamento)
  resultados_naive_bayes.append(accuracy_score(y_teste, naive_bayes.predict(X_teste)))

  logistica = LogisticRegression()
  logistica.fit(X_treinamento, y_treinamento)
  resultados_logistica.append(accuracy_score(y_teste, logistica.predict(X_teste)))

  random_forest = RandomForestClassifier()
  random_forest.fit(X_treinamento, y_treinamento)
  resultados_forest.append(accuracy_score(y_teste, random_forest.predict(X_teste)))

In [ ]:
print(resultados_naive_bayes)

[0.925, 0.925, 0.9325, 0.925, 0.92, 0.905, 0.9175, 0.9175, 0.9125, 0.9325, 0.9225, 0.9125, 0.935, 0.9175, 0.925, 0.9175, 0.9275, 0.92, 0.9325, 0.92, 0.93, 0.905, 0.9175, 0.9325, 0.9425, 0.9375, 0.94, 0.92, 0.935, 0.925]


In [ ]:
print(resultados_logistica)

[0.9325, 0.91, 0.9125, 0.9225, 0.9075, 0.89, 0.91, 0.9075, 0.8775, 0.915, 0.9175, 0.9, 0.925, 0.9175, 0.9025, 0.9125, 0.9525, 0.91, 0.9225, 0.9075, 0.925, 0.905, 0.9075, 0.945, 0.9225, 0.9275, 0.9225, 0.9175, 0.91, 0.9]


In [ ]:
print(resultados_forest)

[0.98, 0.985, 0.9825, 0.9925, 0.9775, 0.9875, 0.985, 0.9875, 0.9775, 0.99, 0.9775, 0.9775, 0.9725, 0.9875, 0.98, 0.9725, 0.9875, 0.985, 0.99, 0.9875, 0.9825, 0.9825, 0.985, 0.9875, 0.9875, 0.995, 0.99, 0.985, 0.9875, 0.9825]


In [ ]:
type(resultados_naive_bayes)

list

In [ ]:
resultados_naive_bayes = np.array(resultados_naive_bayes)
resultados_logistica = np.array(resultados_logistica)
resultados_forest = np.array(resultados_forest)

In [ ]:
type(resultados_naive_bayes)

numpy.ndarray

### Média

In [ ]:
resultados_naive_bayes.mean(), resultados_logistica.mean(), resultados_forest.mean()

(0.92425, 0.9145, 0.9842500000000001)

### Moda

In [ ]:
statistics.mode(resultados_naive_bayes)

In [ ]:
stats.mode(resultados_naive_bayes), stats.mode(resultados_logistica), stats.mode(resultados_forest)

(ModeResult(mode=array([0.9175]), count=array([5])),
 ModeResult(mode=array([0.9075]), count=array([4])),
 ModeResult(mode=array([0.9875]), count=array([8])))

### Mediana

In [ ]:
np.median(resultados_naive_bayes), np.median(resultados_logistica), np.median(resultados_forest)

(0.925, 0.9125, 0.985)

### Variância

In [ ]:
np.set_printoptions(suppress=True)
np.var(resultados_naive_bayes), np.var(resultados_logistica), np.var(resultados_forest)

(8.756250000000001e-05, 0.00020933333333333337, 2.9229166666666637e-05)

In [ ]:
np.min([8.756250000000001e-05, 0.00020933333333333337, 2.9229166666666637e-05])

2.9229166666666637e-05

In [ ]:
np.max([8.756250000000001e-05, 0.00020933333333333337, 2.9229166666666637e-05])

0.00020933333333333337

In [ ]:
resultados_forest

array([0.98  , 0.985 , 0.9825, 0.9925, 0.9775, 0.9875, 0.985 , 0.9875,
       0.9775, 0.99  , 0.9775, 0.9775, 0.9725, 0.9875, 0.98  , 0.9725,
       0.9875, 0.985 , 0.99  , 0.9875, 0.9825, 0.9825, 0.985 , 0.9875,
       0.9875, 0.995 , 0.99  , 0.985 , 0.9875, 0.9825])

### Desvio padrão

In [ ]:
np.std(resultados_naive_bayes), np.std(resultados_logistica), np.std(resultados_forest)

(0.00935748363610645, 0.014468356276140472, 0.005406400527769528)

### Coeficiente de variação

In [ ]:
stats.variation(resultados_naive_bayes) * 100, stats.variation(resultados_logistica) * 100, stats.variation(resultados_forest) * 100

(1.0124407504578252, 1.5821056616884057, 0.6181499161087017)

### Exercício: validação cruzada

In [ ]:
from sklearn.model_selection import cross_val_score, KFold

In [ ]:
resultados_naive_bayes_cv = []
resultados_logistica_cv = []
resultados_forest_cv = []
for i in range(30):
  kfold = KFold(n_splits = 10, shuffle = True, random_state = i)
  
  naive_bayes = GaussianNB()
  scores = cross_val_score(naive_bayes, X, y, cv = kfold)
  resultados_naive_bayes_cv.append(scores.mean())

  logistica = LogisticRegression()
  scores = cross_val_score(logistica, X, y, cv = kfold)
  resultados_logistica_cv.append(scores.mean())
  
  random_forest = RandomForestClassifier()
  scores = cross_val_score(random_forest, X, y, cv = kfold)
  resultados_forest_cv.append(scores.mean())

In [ ]:
scores, 10 * 30

(array([0.995     , 0.985     , 0.985     , 0.99      , 0.97      ,
        0.985     , 0.985     , 0.98492462, 0.98492462, 1.        ]), 300)

In [ ]:
scores.mean()

0.9864849246231155

In [ ]:
print(resultados_naive_bayes_cv)

[0.9248618090452261, 0.9249170854271356, 0.9248894472361808, 0.9228819095477387, 0.9248718592964824, 0.9253894472361809, 0.9243844221105528, 0.9248894472361808, 0.9248718592964824, 0.9238894472361808, 0.9253844221105527, 0.9244020100502512, 0.9253743718592965, 0.924394472361809, 0.9253869346733667, 0.9248819095477387, 0.9258844221105527, 0.924894472361809, 0.9238819095477387, 0.9258844221105529, 0.9258944723618091, 0.9253894472361811, 0.92436432160804, 0.9263844221105527, 0.9228944723618092, 0.9253894472361809, 0.9248869346733668, 0.9253919597989949, 0.9253819095477386, 0.9258844221105527]


In [ ]:
print(resultados_logistica_cv)

[0.9113718592964826, 0.9103668341708543, 0.918359296482412, 0.9158768844221106, 0.9133417085427136, 0.9108718592964824, 0.9188366834170856, 0.9188969849246231, 0.913356783919598, 0.9148693467336683, 0.9098718592964824, 0.9183542713567838, 0.9183793969849248, 0.9213618090452261, 0.9098643216080402, 0.914356783919598, 0.9103693467336684, 0.915856783919598, 0.9128542713567839, 0.9123668341708543, 0.9208944723618091, 0.9108668341708542, 0.9103467336683417, 0.9133768844221105, 0.9098592964824121, 0.9148768844221105, 0.910859296482412, 0.9113768844221104, 0.9113668341708543, 0.9098442211055277]


In [ ]:
print(resultados_forest_cv)

[0.9859748743718593, 0.9864874371859296, 0.9864773869346735, 0.9879773869346733, 0.9894849246231155, 0.9864824120603014, 0.9859723618090452, 0.9864824120603014, 0.9874723618090453, 0.9869824120603015, 0.9879798994974875, 0.9859723618090452, 0.9879773869346735, 0.9869773869346734, 0.9869874371859296, 0.9889824120603015, 0.9859849246231157, 0.9874723618090453, 0.9864824120603014, 0.9849824120603016, 0.9849723618090452, 0.9869798994974875, 0.9844723618090454, 0.9864798994974875, 0.9849773869346734, 0.9869924623115578, 0.9874798994974874, 0.9864773869346735, 0.9894899497487437, 0.9864849246231155]


In [ ]:
stats.variation(resultados_naive_bayes) * 100, stats.variation(resultados_logistica) * 100, stats.variation(resultados_forest) * 100

(1.0124407504578252, 1.5821056616884057, 0.6181499161087017)

In [ ]:
stats.variation(resultados_naive_bayes_cv) * 100, stats.variation(resultados_logistica_cv) * 100, stats.variation(resultados_forest_cv) * 100

(0.08641071566366061, 0.38801026116292653, 0.12246133192106072)

### Seleção de atributos utilizando variância

In [ ]:
np.random.rand(50)

array([0.60767727, 0.53139417, 0.35685462, 0.60524711, 0.52155784,
       0.77232134, 0.12292969, 0.69660273, 0.49254756, 0.65100282,
       0.34159295, 0.5386109 , 0.5768272 , 0.3730196 , 0.85217863,
       0.6627709 , 0.13731565, 0.14989697, 0.2584158 , 0.49596913,
       0.9954359 , 0.52765734, 0.02400514, 0.86547303, 0.49433286,
       0.58474895, 0.86313258, 0.36092719, 0.78650278, 0.82395383,
       0.23511079, 0.22529197, 0.7016215 , 0.82153113, 0.46487207,
       0.92044056, 0.41634674, 0.11610979, 0.58209581, 0.65433692,
       0.19275824, 0.14428809, 0.69976739, 0.19229078, 0.71513706,
       0.89888786, 0.70902675, 0.56468952, 0.64470933, 0.62125035])

In [ ]:
np.random.randint(0, 2)

1

In [ ]:
base_selecao = {'a': np.random.rand(20),
                'b': np.array([0.5] * 20),
                'classe': np.random.randint(0, 2, size = 20)}

In [ ]:
base_selecao

{'a': array([0.93324773, 0.58660345, 0.55414004, 0.72035362, 0.45905076,
        0.18396703, 0.52844755, 0.23956268, 0.90010502, 0.94486426,
        0.95631283, 0.98206372, 0.90325655, 0.19167074, 0.59659936,
        0.68058413, 0.25189904, 0.02985226, 0.60172234, 0.82835921]),
 'b': array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]),
 'classe': array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1])}

In [ ]:
dataset = pd.DataFrame(base_selecao)
dataset.head()

a    b  classe
0  0.933248  0.5       0
1  0.586603  0.5       0
2  0.554140  0.5       1
3  0.720354  0.5       0
4  0.459051  0.5       0

In [ ]:
dataset.describe()

a     b     classe
count  20.000000  20.0  20.000000
mean    0.603633   0.5   0.550000
std     0.299215   0.0   0.510418
min     0.029852   0.5   0.000000
25%     0.407263   0.5   0.000000
50%     0.599161   0.5   1.000000
75%     0.900893   0.5   1.000000
max     0.982064   0.5   1.000000

In [ ]:
math.sqrt(0.08505323963215053)

0.2916388856653902

In [ ]:
np.var(dataset['a']), np.var(dataset['b'])

(0.08505323963215053, 0.0)

In [ ]:
X = dataset.iloc[:, 0:2].values
X

array([[0.93324773, 0.5       ],
       [0.58660345, 0.5       ],
       [0.55414004, 0.5       ],
       [0.72035362, 0.5       ],
       [0.45905076, 0.5       ],
       [0.18396703, 0.5       ],
       [0.52844755, 0.5       ],
       [0.23956268, 0.5       ],
       [0.90010502, 0.5       ],
       [0.94486426, 0.5       ],
       [0.95631283, 0.5       ],
       [0.98206372, 0.5       ],
       [0.90325655, 0.5       ],
       [0.19167074, 0.5       ],
       [0.59659936, 0.5       ],
       [0.68058413, 0.5       ],
       [0.25189904, 0.5       ],
       [0.02985226, 0.5       ],
       [0.60172234, 0.5       ],
       [0.82835921, 0.5       ]])

In [ ]:
from sklearn.feature_selection import VarianceThreshold

In [ ]:
selecao = VarianceThreshold(threshold=0.07)
X_novo = selecao.fit_transform(X)

In [ ]:
X_novo, X_novo.shape

(array([[0.93324773],
        [0.58660345],
        [0.55414004],
        [0.72035362],
        [0.45905076],
        [0.18396703],
        [0.52844755],
        [0.23956268],
        [0.90010502],
        [0.94486426],
        [0.95631283],
        [0.98206372],
        [0.90325655],
        [0.19167074],
        [0.59659936],
        [0.68058413],
        [0.25189904],
        [0.02985226],
        [0.60172234],
        [0.82835921]]), (20, 1))

In [ ]:
selecao.variances_

array([0.08505324, 0.        ])

In [ ]:
indices = np.where(selecao.variances_ > 0.07)
indices

(array([0]),)

#### Exercício seleção de atributos utilizando variância

In [ ]:
dataset = pd.read_csv('credit_data.csv')

In [ ]:
dataset.dropna(inplace=True)

In [ ]:
dataset.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [ ]:
dataset.describe()

i#clientid        income          age          loan    c#default
count  1997.000000   1997.000000  1997.000000   1997.000000  1997.000000
mean   1001.956935  45333.864334    40.807559   4445.487716     0.141713
std     576.702206  14325.131177    13.624469   3046.792457     0.348842
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     503.000000  32804.904487    28.990415   1936.813257     0.000000
50%    1002.000000  45788.747100    41.317159   3977.287432     0.000000
75%    1501.000000  57787.565659    52.587040   6440.861434     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [ ]:
X = dataset.iloc[:, 1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [ ]:
y = dataset.iloc[:, 4].values
y

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [ ]:
X

array([[0.9231759 , 0.95743135, 0.58883739],
       [0.28812165, 0.86378597, 0.47682695],
       [0.74633429, 0.99257918, 0.58262011],
       ...,
       [0.48612202, 0.69109837, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.93282208, 0.53597028]])

In [ ]:
selecao = VarianceThreshold(threshold=0.027)
X_novo = selecao.fit_transform(X)

In [ ]:
X_novo

array([[0.9231759 , 0.58883739],
       [0.28812165, 0.47682695],
       [0.74633429, 0.58262011],
       ...,
       [0.48612202, 0.40112895],
       [0.47500998, 0.1177903 ],
       [0.98881367, 0.53597028]])

In [ ]:
np.var(X[0]), np.var(X[1]), np.var(X[2])

(0.027646353650092215, 0.057415153407223446, 0.02838948027619903)

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
naive_sem_selecao = GaussianNB()
naive_sem_selecao.fit(X, y)
previsoes = naive_sem_selecao.predict(X)
accuracy_score(previsoes, y)

0.9253880821231848

In [ ]:
naive_com_selecao = GaussianNB()
naive_com_selecao.fit(X_novo, y)
previsoes = naive_com_selecao.predict(X_novo)
accuracy_score(previsoes, y)

0.8472709063595393

## Valores faltantes com média e moda

### Média

In [ ]:
import pandas as pd
dataset = pd.read_csv('credit_data.csv')

In [ ]:
dataset.isnull().sum()

i#clientid    0
income        0
age           3
loan          0
c#default     0
dtype: int64

In [ ]:
nulos = dataset[dataset.isnull().any(axis=1)]
nulos

i#clientid        income  age         loan  c#default
28          29  59417.805406  NaN  2082.625938          0
30          31  48528.852796  NaN  6155.784670          0
31          32  23526.302555  NaN  2862.010139          0

In [ ]:
dataset['age'].mean(), dataset['age'].median()

(40.80755937840458, 41.3171591130085)

In [ ]:
dataset['age'] = dataset['age'].replace(to_replace = np.nan, value = dataset['age'].mean())

In [ ]:
dataset[dataset.isnull().any(axis=1)]

Empty DataFrame
Columns: [i#clientid, income, age, loan, c#default]
Index: []

### Moda

In [ ]:
dataset = pd.read_csv('autos.csv', encoding='ISO-8859-1')

In [ ]:
dataset.head()

dateCrawled  ...             lastSeen
0  2016-03-24 11:52:17  ...  2016-04-07 03:16:57
1  2016-03-24 10:58:45  ...  2016-04-07 01:46:50
2  2016-03-14 12:52:21  ...  2016-04-05 12:47:46
3  2016-03-17 16:54:04  ...  2016-03-17 17:40:17
4  2016-03-31 17:25:20  ...  2016-04-06 10:17:21

[5 rows x 20 columns]

In [ ]:
dataset.isnull().sum()

dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [ ]:
dataset['fuelType'].unique()

array(['benzin', 'diesel', nan, 'lpg', 'andere', 'hybrid', 'cng',
       'elektro'], dtype=object)

In [ ]:
stats.mode(dataset['fuelType'])

ModeResult(mode=array(['benzin'], dtype=object), count=array([223857]))

In [ ]:
statistics.mode(dataset['fuelType'])

'benzin'

In [ ]:
dataset['fuelType'] = dataset['fuelType'].replace(to_replace = np.nan, value = statistics.mode(dataset['fuelType']))

In [ ]:
dataset['fuelType'].unique()

array(['benzin', 'diesel', 'lpg', 'andere', 'hybrid', 'cng', 'elektro'],
      dtype=object)